# Site Settings
name: Gabby Blog
title: Gabby Blog | Home
description: Hey i am Gabriel!
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: https://blog.gjdev.it
  - title: Arena Giovani
    url: https://comune.arena-giovai.gjdev.it
  - title: Gabriel Jones
    url: https://gabrieljones.gjdev.it
  - title: contatti 
    url: https://gabrieljones.gjdev.it/contatti/
  - title: Gabriel Jones
    url: https://archives.gabrieljones.gjdev.it/so/gjd/
email: gabriel.jones@mail.urp.gjdev.it
# See: https://disqus.com/
# Contact Form Setting
# See: https://formspree.io/

# Social Media Settings
# Remove the item if you don't need it
github_username: gabrieljonesdev
twitter_username: gabrieljonesdev
instagram_username: onlygabbyme
medium_username: gabrieljonesdev


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.gjdev.it" # the base hostname & protocol for your site
language: "it"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

sent_message_url: /thank-you
formspree_form_id: xwpknlql
contact:
  title: "Talk to me"
  placeholders:
    name: "Your name"
    email: "Your email"
    message: "Your message"
  submit_btn: "Send"
  subject: "New contact!"
  errors:
    locale: "en"
    empty_name: "Please enter your name"
    empty_email: "Please enter your email"
    invalid_email: "Please enter a valid email"
    empty_message: "Please enter a message"


exclude: [
  'docs/',
  'vendor/',
  'LICENSE',
  'CHANGELOG.md',
  'jekflix.gemspec',
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: "pages"


